import { Categories } from "@/types";

export const categories: Categories[] = [
  {
    id: 1,
    name: "Electronics",
    slug: "electronics",
    image: "electronics.jpg",
    description: "Latest gadgets, smartphones, laptops, and accessories.",
    link: "/categories/electronics",
  },
  {
    id: 2,
    name: "Fashion",
    slug: "fashion",
    image: "fashion.jpg",
    description: "Trendy clothing, shoes, and accessories for all genders.",
    link: "/categories/fashion",
  },
  {
    id: 3,
    name: "Home & Kitchen",
    slug: "home-kitchen",
    image: "home-kitchen.jpg",
    description: "Furniture, appliances, cookware, and home decor.",
    link: "/categories/home-kitchen",
  },
  {
    id: 4,
    name: "Beauty & Personal Care",
    slug: "beauty-personal-care",
    image: "beauty.jpg",
    description: "Skincare, haircare, cosmetics, and grooming essentials.",
    link: "/categories/Beauty",
  },
  {
    id: 5,
    name: "Sports & Outdoors",
    slug: "sports-outdoors",
    image: "sports.jpg",
    description: "Fitness gear, outdoor equipment, and activewear.",
    link: "/categories/sports",
  },
  {
    id: 6,
    name: "Books & Stationery",
    slug: "books-stationery",
    image: "books.jpg",
    description: "Novels, textbooks, journals, and office supplies.",
    link: "/categories/books",
  },
  {
    id: 7,
    name: "Toys & Games",
    slug: "toys-games",
    image: "toys.jpg",
    description: "Fun and educational toys for kids of all ages.",
    link: "/categories/toys",
  },
  {
    id: 8,
    name: "Automotive",
    slug: "automotive",
    image: "automotive.jpg",
    description: "Car accessories, tools, and maintenance products.",
    link: "/categories/Automotive",
  },
  {
    id: 9,
    name: "Health & Wellness",
    slug: "health-wellness",
    image: "health.jpg",
    description: "Supplements, fitness trackers, and wellness products.",
    link: "/categories/health",
  },
  {
    id: 10,
    name: "Pet Supplies",
    slug: "pet-supplies",
    image: "pets.jpg",
    description: "Food, toys, and accessories for your furry friends.",
    link: "/categories/Pet",
  },
];
